pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  inputs:
    targetType: inline
    script: $PSVersionTable.PSVersion
    pwsh: false
- task: PowerShell@2
  inputs:
    targetType: inline
    script: $PSVersionTable.PSVersion
    pwsh: true
- pwsh: $PSVersionTable.PSVersion
