steps:
- checkout: self
  clean: true
- powershell:
  inputs: $PSVersionTable.PSVersion
  pwsh: false
- powershell:
  inputs: $PSVersionTable.PSVersion
  pwsh: true
- pwsh:
  inputs: $PSVersionTable.PSVersion
  pwsh: false
- pwsh:
  inputs: $PSVersionTable.PSVersion
  pwsh: true
